import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const aspektaSans = localFont({
  src: "./fonts/AspektaVF.woff2",
  variable: "--font-aspekta-sans",
  weight: "100 950",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${aspektaSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
